from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = ROOT / "data" / "booking-hotels-extracted.json"
OUTPUT_PATH = ROOT / "data" / "booking-hotels-seed.sql"


def sql_quote(value: str | None) -> str:
	if value is None:
		return "NULL"
	escaped = value.replace("'", "''")
	return f"'{escaped}'"


def sql_bool(value: bool | None) -> str:
	if value is None:
		return "NULL"
	return "true" if value else "false"


def sql_number(value: int | float | None) -> str:
	if value is None:
		return "NULL"
	if isinstance(value, float):
		value = round(value)
	return str(int(value))


def build_description(hotel: dict) -> str:
	name = hotel.get("name") or "Этот объект"
	city = hotel.get("city") or "городе"
	country = hotel.get("country")
	category = hotel.get("category") or "вариант размещения"
	rating = hotel.get("rating")
	reviews = hotel.get("reviews_count")
	address = hotel.get("address")

	parts = [f"{name} — {category.lower()} в {city}"]
	if country:
		parts[-1] += f", {country}"
	if address:
		parts[-1] += f", по адресу {address}"
	parts[-1] += "."

	if rating:
		review_text = f"Оценка гостей: {rating}"
		if reviews:
			review_text += f" на основе {reviews} отзывов"
		parts.append(review_text + ".")

	parts.append("Данные карточки и главное изображение импортированы из сохранённой страницы Booking.")
	return " ".join(parts)


def build_row(hotel: dict) -> str:
	row = [
		sql_quote(hotel.get("name")),
		sql_quote(hotel.get("city")),
		sql_quote(hotel.get("country")),
		sql_quote(hotel.get("address")),
		sql_number(hotel.get("stars") or 0),
		sql_number(hotel.get("rating")),
		sql_number(hotel.get("reviews_count")),
		sql_number(hotel.get("price_unformatted")),
		sql_number(hotel.get("old_price_unformatted")),
		sql_quote(hotel.get("category") or "Гостиница"),
		sql_bool(hotel.get("is_genius") or False),
		sql_quote(hotel.get("image_url") or hotel.get("image_preview_url")),
		sql_quote(build_description(hotel)),
	]
	return f"({', '.join(row)})"


def main() -> None:
	payload = json.loads(INPUT_PATH.read_text(encoding="utf-8"))
	hotels = []
	for file_group in payload.get("files", []):
		hotels.extend(file_group.get("hotels", []))

	cities = sorted({hotel.get("city") for hotel in hotels if hotel.get("city")})
	city_list = ", ".join(sql_quote(city) for city in cities)
	rows = ",\n".join(build_row(hotel) for hotel in hotels if hotel.get("name"))

	sql = f"""-- ============================================================
-- HOTELS SEED — extracted from saved Booking HTML pages
-- Generated by scripts/generate_hotels_seed_sql.py
-- Source JSON: data/booking-hotels-extracted.json
-- Total hotels: {len(hotels)}
-- ============================================================

DELETE FROM hotels
WHERE city IN ({city_list});

INSERT INTO hotels (
  name,
  city,
  country,
  address,
  stars,
  rating,
  reviews_count,
  price_per_night,
  original_price,
  category,
  is_genius,
  image_url,
  description
) VALUES
{rows};

SELECT city, COUNT(*) AS hotels_count
FROM hotels
WHERE city IN ({city_list})
GROUP BY city
ORDER BY city;
"""

	OUTPUT_PATH.write_text(sql, encoding="utf-8")
	print(f"Saved SQL seed to {OUTPUT_PATH}")
	print(f"Cities: {', '.join(cities)}")
	print(f"Hotels: {len(hotels)}")


if __name__ == "__main__":
	main()
